

package com.bnorm.power.box;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.bnorm.power.runners.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/test/data/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
    @Test
    public void testAllFilesPresentInBox() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("CheckCustomMessage.kt")
    public void testCheckCustomMessage() throws Exception {
        runTest("src/test/data/box/CheckCustomMessage.kt");
    }

    @Test
    @TestMetadata("Constants.kt")
    public void testConstants() throws Exception {
        runTest("src/test/data/box/Constants.kt");
    }

    @Test
    @TestMetadata("CustomLocalVariableMessage.kt")
    public void testCustomLocalVariableMessage() throws Exception {
        runTest("src/test/data/box/CustomLocalVariableMessage.kt");
    }

    @Test
    @TestMetadata("CustomMessage.kt")
    public void testCustomMessage() throws Exception {
        runTest("src/test/data/box/CustomMessage.kt");
    }

    @Test
    @TestMetadata("MemberFunctions.kt")
    public void testMemberFunctions() throws Exception {
        runTest("src/test/data/box/MemberFunctions.kt");
    }

    @Test
    @TestMetadata("Multiline.kt")
    public void testMultiline() throws Exception {
        runTest("src/test/data/box/Multiline.kt");
    }

    @Test
    @TestMetadata("RequireCustomMessage.kt")
    public void testRequireCustomMessage() throws Exception {
        runTest("src/test/data/box/RequireCustomMessage.kt");
    }

    @Test
    @TestMetadata("Transformations.kt")
    public void testTransformations() throws Exception {
        runTest("src/test/data/box/Transformations.kt");
    }

    @Nested
    @TestMetadata("src/test/data/box/arithmetic")
    @TestDataPath("$PROJECT_ROOT")
    public class Arithmetic {
        @Test
        public void testAllFilesPresentInArithmetic() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/arithmetic"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("InlineAddition.kt")
        public void testInlineAddition() throws Exception {
            runTest("src/test/data/box/arithmetic/InlineAddition.kt");
        }

        @Test
        @TestMetadata("InlineDivision.kt")
        public void testInlineDivision() throws Exception {
            runTest("src/test/data/box/arithmetic/InlineDivision.kt");
        }

        @Test
        @TestMetadata("InlineMultiplication.kt")
        public void testInlineMultiplication() throws Exception {
            runTest("src/test/data/box/arithmetic/InlineMultiplication.kt");
        }

        @Test
        @TestMetadata("InlinePostfixDecrement.kt")
        public void testInlinePostfixDecrement() throws Exception {
            runTest("src/test/data/box/arithmetic/InlinePostfixDecrement.kt");
        }

        @Test
        @TestMetadata("InlinePostfixIncrement.kt")
        public void testInlinePostfixIncrement() throws Exception {
            runTest("src/test/data/box/arithmetic/InlinePostfixIncrement.kt");
        }

        @Test
        @TestMetadata("InlinePrefixDecrement.kt")
        public void testInlinePrefixDecrement() throws Exception {
            runTest("src/test/data/box/arithmetic/InlinePrefixDecrement.kt");
        }

        @Test
        @TestMetadata("InlinePrefixIncrement.kt")
        public void testInlinePrefixIncrement() throws Exception {
            runTest("src/test/data/box/arithmetic/InlinePrefixIncrement.kt");
        }

        @Test
        @TestMetadata("InlineSubtraction.kt")
        public void testInlineSubtraction() throws Exception {
            runTest("src/test/data/box/arithmetic/InlineSubtraction.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/boolean")
    @TestDataPath("$PROJECT_ROOT")
    public class Boolean {
        @Test
        public void testAllFilesPresentInBoolean() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/boolean"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("BooleanAnd.kt")
        public void testBooleanAnd() throws Exception {
            runTest("src/test/data/box/boolean/BooleanAnd.kt");
        }

        @Test
        @TestMetadata("BooleanMixWithAndFirst.kt")
        public void testBooleanMixWithAndFirst() throws Exception {
            runTest("src/test/data/box/boolean/BooleanMixWithAndFirst.kt");
        }

        @Test
        @TestMetadata("BooleanMixWithAndLast.kt")
        public void testBooleanMixWithAndLast() throws Exception {
            runTest("src/test/data/box/boolean/BooleanMixWithAndLast.kt");
        }

        @Test
        @TestMetadata("BooleanMixWithOrFirst.kt")
        public void testBooleanMixWithOrFirst() throws Exception {
            runTest("src/test/data/box/boolean/BooleanMixWithOrFirst.kt");
        }

        @Test
        @TestMetadata("BooleanMixWithOrLast.kt")
        public void testBooleanMixWithOrLast() throws Exception {
            runTest("src/test/data/box/boolean/BooleanMixWithOrLast.kt");
        }

        @Test
        @TestMetadata("BooleanOr.kt")
        public void testBooleanOr() throws Exception {
            runTest("src/test/data/box/boolean/BooleanOr.kt");
        }

        @Test
        @TestMetadata("BooleanShortCircuit.kt")
        public void testBooleanShortCircuit() throws Exception {
            runTest("src/test/data/box/boolean/BooleanShortCircuit.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/cast")
    @TestDataPath("$PROJECT_ROOT")
    public class Cast {
        @Test
        public void testAllFilesPresentInCast() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/cast"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("InstanceEquals.kt")
        public void testInstanceEquals() throws Exception {
            runTest("src/test/data/box/cast/InstanceEquals.kt");
        }

        @Test
        @TestMetadata("InstanceNotEquals.kt")
        public void testInstanceNotEquals() throws Exception {
            runTest("src/test/data/box/cast/InstanceNotEquals.kt");
        }

        @Test
        @TestMetadata("SmartCast.kt")
        public void testSmartCast() throws Exception {
            runTest("src/test/data/box/cast/SmartCast.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/dbg")
    @TestDataPath("$PROJECT_ROOT")
    public class Dbg {
        @Test
        public void testAllFilesPresentInDbg() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/dbg"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("DebugEntryFunction.kt")
        public void testDebugEntryFunction() throws Exception {
            runTest("src/test/data/box/dbg/DebugEntryFunction.kt");
        }

        @Test
        @TestMetadata("DebugEntryFunctionComplexBooleans.kt")
        public void testDebugEntryFunctionComplexBooleans() throws Exception {
            runTest("src/test/data/box/dbg/DebugEntryFunctionComplexBooleans.kt");
        }

        @Test
        @TestMetadata("DebugEntryFunctionMessage.kt")
        public void testDebugEntryFunctionMessage() throws Exception {
            runTest("src/test/data/box/dbg/DebugEntryFunctionMessage.kt");
        }

        @Test
        @TestMetadata("DebugEntryFunctionMessageComplexBooleans.kt")
        public void testDebugEntryFunctionMessageComplexBooleans() throws Exception {
            runTest("src/test/data/box/dbg/DebugEntryFunctionMessageComplexBooleans.kt");
        }

        @Test
        @TestMetadata("DebugFunction.kt")
        public void testDebugFunction() throws Exception {
            runTest("src/test/data/box/dbg/DebugFunction.kt");
        }

        @Test
        @TestMetadata("DebugFunctionMessage.kt")
        public void testDebugFunctionMessage() throws Exception {
            runTest("src/test/data/box/dbg/DebugFunctionMessage.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/infix")
    @TestDataPath("$PROJECT_ROOT")
    public class Infix {
        @Test
        public void testAllFilesPresentInInfix() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/infix"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("DispatchInfix.kt")
        public void testDispatchInfix() throws Exception {
            runTest("src/test/data/box/infix/DispatchInfix.kt");
        }

        @Test
        @TestMetadata("DispatchInfixConstantParameter.kt")
        public void testDispatchInfixConstantParameter() throws Exception {
            runTest("src/test/data/box/infix/DispatchInfixConstantParameter.kt");
        }

        @Test
        @TestMetadata("DispatchInfixConstantReceiver.kt")
        public void testDispatchInfixConstantReceiver() throws Exception {
            runTest("src/test/data/box/infix/DispatchInfixConstantReceiver.kt");
        }

        @Test
        @TestMetadata("DispatchInfixOnlyConstants.kt")
        public void testDispatchInfixOnlyConstants() throws Exception {
            runTest("src/test/data/box/infix/DispatchInfixOnlyConstants.kt");
        }

        @Test
        @TestMetadata("DispatchNonInfix.kt")
        public void testDispatchNonInfix() throws Exception {
            runTest("src/test/data/box/infix/DispatchNonInfix.kt");
        }

        @Test
        @TestMetadata("DispatchNonInfixConstantParameter.kt")
        public void testDispatchNonInfixConstantParameter() throws Exception {
            runTest("src/test/data/box/infix/DispatchNonInfixConstantParameter.kt");
        }

        @Test
        @TestMetadata("DispatchNonInfixConstantReceiver.kt")
        public void testDispatchNonInfixConstantReceiver() throws Exception {
            runTest("src/test/data/box/infix/DispatchNonInfixConstantReceiver.kt");
        }

        @Test
        @TestMetadata("DispatchNonInfixOnlyConstants.kt")
        public void testDispatchNonInfixOnlyConstants() throws Exception {
            runTest("src/test/data/box/infix/DispatchNonInfixOnlyConstants.kt");
        }

        @Test
        @TestMetadata("ExtensionInfix.kt")
        public void testExtensionInfix() throws Exception {
            runTest("src/test/data/box/infix/ExtensionInfix.kt");
        }

        @Test
        @TestMetadata("ExtensionInfixConstantParameter.kt")
        public void testExtensionInfixConstantParameter() throws Exception {
            runTest("src/test/data/box/infix/ExtensionInfixConstantParameter.kt");
        }

        @Test
        @TestMetadata("ExtensionInfixConstantReceiver.kt")
        public void testExtensionInfixConstantReceiver() throws Exception {
            runTest("src/test/data/box/infix/ExtensionInfixConstantReceiver.kt");
        }

        @Test
        @TestMetadata("ExtensionInfixOnlyConstants.kt")
        public void testExtensionInfixOnlyConstants() throws Exception {
            runTest("src/test/data/box/infix/ExtensionInfixOnlyConstants.kt");
        }

        @Test
        @TestMetadata("ExtensionNonInfix.kt")
        public void testExtensionNonInfix() throws Exception {
            runTest("src/test/data/box/infix/ExtensionNonInfix.kt");
        }

        @Test
        @TestMetadata("ExtensionNonInfixConstantParameter.kt")
        public void testExtensionNonInfixConstantParameter() throws Exception {
            runTest("src/test/data/box/infix/ExtensionNonInfixConstantParameter.kt");
        }

        @Test
        @TestMetadata("ExtensionNonInfixConstantReceiver.kt")
        public void testExtensionNonInfixConstantReceiver() throws Exception {
            runTest("src/test/data/box/infix/ExtensionNonInfixConstantReceiver.kt");
        }

        @Test
        @TestMetadata("ExtensionNonInfixOnlyConstants.kt")
        public void testExtensionNonInfixOnlyConstants() throws Exception {
            runTest("src/test/data/box/infix/ExtensionNonInfixOnlyConstants.kt");
        }

        @Test
        @TestMetadata("RegexFunction.kt")
        public void testRegexFunction() throws Exception {
            runTest("src/test/data/box/infix/RegexFunction.kt");
        }

        @Test
        @TestMetadata("RegexInfix.kt")
        public void testRegexInfix() throws Exception {
            runTest("src/test/data/box/infix/RegexInfix.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/junit5")
    @TestDataPath("$PROJECT_ROOT")
    public class Junit5 {
        @Test
        public void testAllFilesPresentInJunit5() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/junit5"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("JunitAssertTrue.kt")
        public void testJunitAssertTrue() throws Exception {
            runTest("src/test/data/box/junit5/JunitAssertTrue.kt");
        }

        @Test
        @TestMetadata("JunitAssertTrueMessage.kt")
        public void testJunitAssertTrueMessage() throws Exception {
            runTest("src/test/data/box/junit5/JunitAssertTrueMessage.kt");
        }

        @Test
        @TestMetadata("JunitAssertTrueMessageSupplier.kt")
        public void testJunitAssertTrueMessageSupplier() throws Exception {
            runTest("src/test/data/box/junit5/JunitAssertTrueMessageSupplier.kt");
        }

        @Test
        @TestMetadata("JunitAssertTrueMessageSupplierVariable.kt")
        public void testJunitAssertTrueMessageSupplierVariable() throws Exception {
            runTest("src/test/data/box/junit5/JunitAssertTrueMessageSupplierVariable.kt");
        }

        @Test
        @TestMetadata("JunitAssertTrueMessageVariable.kt")
        public void testJunitAssertTrueMessageVariable() throws Exception {
            runTest("src/test/data/box/junit5/JunitAssertTrueMessageVariable.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/kotlin-test")
    @TestDataPath("$PROJECT_ROOT")
    public class Kotlin_test {
        @Test
        public void testAllFilesPresentInKotlin_test() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/kotlin-test"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("AssertEquals.kt")
        public void testAssertEquals() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertEquals.kt");
        }

        @Test
        @TestMetadata("AssertEqualsMessage.kt")
        public void testAssertEqualsMessage() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertEqualsMessage.kt");
        }

        @Test
        @TestMetadata("AssertEqualsMessageVariable.kt")
        public void testAssertEqualsMessageVariable() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertEqualsMessageVariable.kt");
        }

        @Test
        @TestMetadata("AssertFalse.kt")
        public void testAssertFalse() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertFalse.kt");
        }

        @Test
        @TestMetadata("AssertFalseMessage.kt")
        public void testAssertFalseMessage() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertFalseMessage.kt");
        }

        @Test
        @TestMetadata("AssertFalseMessageVariable.kt")
        public void testAssertFalseMessageVariable() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertFalseMessageVariable.kt");
        }

        @Test
        @TestMetadata("AssertNotNull.kt")
        public void testAssertNotNull() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertNotNull.kt");
        }

        @Test
        @TestMetadata("AssertNotNullMessage.kt")
        public void testAssertNotNullMessage() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertNotNullMessage.kt");
        }

        @Test
        @TestMetadata("AssertNotNullMessageVariable.kt")
        public void testAssertNotNullMessageVariable() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertNotNullMessageVariable.kt");
        }

        @Test
        @TestMetadata("AssertTrue.kt")
        public void testAssertTrue() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertTrue.kt");
        }

        @Test
        @TestMetadata("AssertTrueMessage.kt")
        public void testAssertTrueMessage() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertTrueMessage.kt");
        }

        @Test
        @TestMetadata("AssertTrueMessageVariable.kt")
        public void testAssertTrueMessageVariable() throws Exception {
            runTest("src/test/data/box/kotlin-test/AssertTrueMessageVariable.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/lambda")
    @TestDataPath("$PROJECT_ROOT")
    public class Lambda {
        @Test
        public void testAllFilesPresentInLambda() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/lambda"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("AnonymousObject.kt")
        public void testAnonymousObject() throws Exception {
            runTest("src/test/data/box/lambda/AnonymousObject.kt");
        }

        @Test
        @TestMetadata("ListOperationsAssert.kt")
        public void testListOperationsAssert() throws Exception {
            runTest("src/test/data/box/lambda/ListOperationsAssert.kt");
        }

        @Test
        @TestMetadata("ListOperationsRequire.kt")
        public void testListOperationsRequire() throws Exception {
            runTest("src/test/data/box/lambda/ListOperationsRequire.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/nullsafe")
    @TestDataPath("$PROJECT_ROOT")
    public class Nullsafe {
        @Test
        public void testAllFilesPresentInNullsafe() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/nullsafe"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("ConditionalAccess.kt")
        public void testConditionalAccess() throws Exception {
            runTest("src/test/data/box/nullsafe/ConditionalAccess.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/operator")
    @TestDataPath("$PROJECT_ROOT")
    public class Operator {
        @Test
        public void testAllFilesPresentInOperator() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/operator"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("ContainsFunction.kt")
        public void testContainsFunction() throws Exception {
            runTest("src/test/data/box/operator/ContainsFunction.kt");
        }

        @Test
        @TestMetadata("ContainsOperator.kt")
        public void testContainsOperator() throws Exception {
            runTest("src/test/data/box/operator/ContainsOperator.kt");
        }

        @Test
        @TestMetadata("NegativeContainsFunction.kt")
        public void testNegativeContainsFunction() throws Exception {
            runTest("src/test/data/box/operator/NegativeContainsFunction.kt");
        }

        @Test
        @TestMetadata("NegativeContainsOperator.kt")
        public void testNegativeContainsOperator() throws Exception {
            runTest("src/test/data/box/operator/NegativeContainsOperator.kt");
        }
    }

    @Nested
    @TestMetadata("src/test/data/box/parameters")
    @TestDataPath("$PROJECT_ROOT")
    public class Parameters {
        @Test
        public void testAllFilesPresentInParameters() throws Exception {
            KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test/data/box/parameters"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
        }

        @Test
        @TestMetadata("VarargParameter.kt")
        public void testVarargParameter() throws Exception {
            runTest("src/test/data/box/parameters/VarargParameter.kt");
        }
    }
}
